# Generated by Django 3.1.2 on 2020-10-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20201023_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='content3',
        ),
    ]
